# Generated by Django 4.1.2 on 2022-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Packing', 'Packing'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], max_length=255, null=True),
        ),
    ]
