# Generated by Django 4.1.2 on 2022-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='default_avatar.jpg', upload_to=''),
        ),
    ]
